openapi: 3.0.0
info:
  title: API de Imagens com Cloudinary
  description: API para upload, listagem e recuperação de imagens armazenadas no Cloudinary.
  version: "1.0.0"

servers:
  - url: http://localhost:3000/api

paths:
  /uploadFile:
    post:
      summary: Faz upload de uma imagem para o Cloudinary
      tags:
        - Imagens
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Arquivo de imagem a ser enviado
      responses:
        "200":
          description: Imagem enviada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  file:
                    type: object
                    properties:
                      image_properties:
                        type: object
                        properties:
                          originalname:
                            type: string
                          typeImage:
                            type: string
                          size:
                            type: integer
                          url:
                            type: string

  /getListAllImages:
    get:
      summary: Lista os `public_id` de todas as imagens armazenadas
      tags:
        - Imagens
      responses:
        "200":
          description: Lista de imagens retornada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  public_ids:
                    type: array
                    items:
                      type: string
        "500":
          description: Erro ao buscar imagens

  /getImage/{id}:
    get:
      summary: Busca a URL de uma imagem pelo seu `public_id`
      tags:
        - Imagens
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: O `public_id` da imagem no Cloudinary
      responses:
        "200":
          description: Imagem encontrada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  url:
                    type: string
        "400":
          description: Public ID ausente
        "500":
          description: Erro ao buscar imagem
